version: '1'

services:
  api:
    container_name: test-api
    restart: always
    build: api/
    volumes:
      - ./api:/usr/src/app/
    ports:
      - 8080:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
      - DB_HOST=${DB_CONTAINER}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  pg_db:
    container_name: ${DB_CONTAINER}
    restart: always
    image: postgres:14
    volumes:
      - ./db/init-scrypts:/docker-entrypoint-initdb.d/
    ports:
      - 5433:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
